metallb:
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 85Mi
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  speaker:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 50Mi
    # Use classic mode for simplicity
    frr:
      enabled: false

  networkpolicies:
    enabled: true
    apiPort: 443
