apiVersion: v2
name: prometheus-blackbox-exporter
description: prometheus-blackbox-exporter for kilchhofer-home
type: application

version: 1.0.0

dependencies:
- name: prometheus-blackbox-exporter
  version: 11.4.2
  repository: oci://ghcr.io/prometheus-community/charts
