apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: istio-ingressgateway
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: core-services-unrestricted
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  source:
    path: umbrella-charts/istio-ingressgateway
    repoURL: 'git@github.com:mkilchhofer/k8s-gitops-services.git'
