unifi:
  ingress:
    enabled: false # We use HTTPRoute instead

  image:
    tag: "" # Use appVersion
  livenessProbe:
    enabled: false

  bindPrivilegedPorts: false
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 999
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    limits:
      cpu: 500m
      memory: 1280Mi
    requests:
      cpu: 10m
      memory: 1100Mi

  extraVolumes:
    - name: tmp-dir
      emptyDir:
        sizeLimit: 1Gi

  extraVolumeMounts:
    - mountPath: /tmp
      name: tmp-dir

  persistence:
    enabled: true
    storageClass: nfs-data

  controllerService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
  guiService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
  discoveryService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
  stunService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
  speedtestService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
  syslogService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "192.168.93.87"
    annotations:
      lbipam.cilium.io/sharing-key: unifi
