apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
spec:
  ports:
  - name: web
    port: 1411
    targetPort: web
  selector:
    app.kubernetes.io/name: pocket-id
