apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: opnsense-peering
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: cilium
      localASN: 64513
      peers:
        - name: opnsense
          peerASN: 64512
          peerAddress: 192.168.92.1
          peerConfigRef:
            name: peer-config-generic
