apiVersion: v2
name: grafana
description: Grafana for kilchhofer-home
type: application

version: 1.0.0

dependencies:
- name: postgresql
  version: 18.3.0
  repository: oci://registry-1.docker.io/bitnamicharts
- name: grafana
  version: 11.1.1
  repository: oci://ghcr.io/grafana-community/helm-charts
