apiVersion: v2
name: prometheus-node-exporter
description: prometheus-node-exporter for kilchhofer-home
type: application

version: 1.0.0

dependencies:
- name: prometheus-node-exporter
  version: 4.49.2
  repository: oci://ghcr.io/prometheus-community/charts
