fluent-bit:
  serviceAccount:
    create: false
  rbac:
    create: false

  kind: Deployment

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 32Mi

  extraPorts:
    - name: syslog
      containerPort: 5140
      protocol: TCP
      port: 5140

  args:
    - --workdir=/fluent-bit/etc
    - --config=/fluent-bit/etc/conf/fluent-bit.yaml

  env:
    - name: LOKI_HOST
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-creds
          key: host
    - name: LOKI_USER
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-creds
          key: user
    - name: LOKI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-creds
          key: password

  config:
    inputs: ""
    outputs: ""
    filters: ""
    extraFiles:
      fluent-bit.yaml: |
        service:
          daemon: Off
          flush: 1
          log_level: info
          parsers_file: /fluent-bit/etc/parsers.conf
          http_server: on

        pipeline:
          inputs:
            - name: syslog
              parser: syslog-rfc3164
              mode: tcp
              port: 5140
            - name: syslog
              parser: syslog-rfc3164
              mode: udp
              port: 5140

          outputs:
            - name: loki
              match: '*'
              host: ${LOKI_HOST}
              http_user: ${LOKI_USER}
              http_passwd: ${LOKI_PASSWORD}
              port: 443
              tls: on
              tls.verify: on
              tenant_id: syslog-rfc3164
              line_format: json
              labels: job=fluent-bit-syslog-rfc3164
              label_keys: $pri,$host,$ident
              remove_keys: time,pid

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.93.85
    annotations:
      lbipam.cilium.io/sharing-key: syslog-rfc3164

  securityContext:
    runAsUser: 1001

